// Clone init — minimal PID 1 for rootfs boot.
//
// This binary runs as /init inside a tiny initrd generated by Clone.
// It mounts the virtio-block rootfs, switches root, and execs /sbin/init.
//
// The kernel command line controls behavior:
//   clone.rootfs=rw    — mount rootfs read-write (default)
//   clone.rootfs=ro    — mount rootfs read-only (for overlay mode)
//   clone.overlay=tmpfs — overlay with tmpfs upper layer
//   clone.overlay=none  — no overlay (default)

use std::ffi::CString;
use std::io::Write;
use std::path::Path;
use std::{fs, thread, time::Duration};

// Mount flags — defined here so this compiles on macOS even though
// the binary only runs inside a Linux guest VM.
const MS_RDONLY: u64 = 1;
const MS_MOVE: u64 = 0x2000;

/// Write a message to the serial port.
/// Uses multiple methods to ensure output is visible:
/// 1. Direct I/O port access (port 0x3F8) — always works
/// 2. /dev/console
/// 3. stdout
fn msg(s: &str) {
    // Method 1: Direct I/O port writes (most reliable, bypasses tty layer)
    serial_write(s);
    serial_write("\n");

    // Method 2: Also try /dev/console for programs that use stdout later
    if let Ok(mut f) = fs::OpenOptions::new().write(true).open("/dev/console") {
        let _ = writeln!(f, "{s}");
    }
}

/// Write a string directly to COM1 (I/O port 0x3F8) using port I/O.
/// Requires iopl(3) to have been called first.
#[cfg(target_os = "linux")]
fn serial_write(s: &str) {
    for &b in s.as_bytes() {
        // Wait for THR empty (LSR bit 5)
        loop {
            let lsr: u8;
            unsafe {
                std::arch::asm!("in al, dx", out("al") lsr, in("dx") 0x3FDu16);
            }
            if lsr & 0x20 != 0 {
                break;
            }
        }
        // Write byte to THR
        unsafe {
            std::arch::asm!("out dx, al", in("al") b, in("dx") 0x3F8u16);
        }
    }
}

#[cfg(not(target_os = "linux"))]
fn serial_write(_s: &str) {}

/// Call iopl(3) to enable I/O port access for direct serial writes.
#[cfg(target_os = "linux")]
fn enable_iopl() {
    unsafe {
        libc::iopl(3);
    }
}

#[cfg(not(target_os = "linux"))]
fn enable_iopl() {}

fn main() {
    enable_iopl();
    msg("[clone-init] starting");

    // Mount basic pseudo-filesystems
    mkdir("/proc");
    mkdir("/sys");
    mkdir("/dev");
    mount_fs("proc", "/proc", "proc", 0);
    mount_fs("sysfs", "/sys", "sysfs", 0);
    mount_fs("devtmpfs", "/dev", "devtmpfs", 0);

    // Load kernel modules from the initrd early — they are embedded by the VMM's
    // rootfs initrd generator and won't be available after we switch root.
    // Must happen before overlay setup (needs overlay.ko) and before agent start (needs vsock).
    for module in &[
        "/lib/modules/vsock.ko",
        "/lib/modules/vmw_vsock_virtio_transport_common.ko",
        "/lib/modules/vmw_vsock_virtio_transport.ko",
        "/lib/modules/overlay.ko",
    ] {
        if Path::new(module).exists() {
            load_module(module);
        }
    }

    // Parse kernel command line
    let cmdline = read_cmdline();
    let rootfs_mode = parse_param(&cmdline, "clone.rootfs").unwrap_or("rw");
    let overlay_mode = parse_param(&cmdline, "clone.overlay").unwrap_or("none");
    let rootfs_type = parse_param(&cmdline, "clone.fstype").unwrap_or("auto");

    msg(&format!("[clone-init] rootfs={rootfs_mode} overlay={overlay_mode} fstype={rootfs_type}"));

    // Wait for the root block device to appear
    let root_dev = "/dev/vda";
    wait_for_device(root_dev);

    // Mount rootfs
    mkdir("/mnt");
    mkdir("/mnt/root");

    let mount_flags: u64 = if rootfs_mode == "ro" {
        MS_RDONLY
    } else {
        0
    };

    if rootfs_type == "auto" {
        // Try common filesystems
        let tried = ["ext4", "xfs", "btrfs", "ext3", "ext2"];
        let mut mounted = false;
        for fstype in &tried {
            if mount_fs(root_dev, "/mnt/root", fstype, mount_flags) {
                msg(&format!("[clone-init] mounted {root_dev} as {fstype}"));
                mounted = true;
                break;
            }
        }
        if !mounted {
            panic!("[clone-init] failed to mount {root_dev} with any filesystem");
        }
    } else {
        if !mount_fs(root_dev, "/mnt/root", rootfs_type, mount_flags) {
            panic!("[clone-init] failed to mount {root_dev} as {rootfs_type}");
        }
    }

    // Handle overlay mode
    let real_root = if overlay_mode == "tmpfs" {
        setup_overlay_tmpfs()
    } else if overlay_mode == "block" {
        setup_overlay_block()
    } else {
        "/mnt/root"
    };

    // Ensure target directories exist for mount moves
    mkdir(&format!("{real_root}/proc"));
    mkdir(&format!("{real_root}/sys"));
    mkdir(&format!("{real_root}/dev"));
    mkdir(&format!("{real_root}/mnt"));

    // Move pseudo-filesystems into new root
    mount_move("/proc", &format!("{real_root}/proc"));
    mount_move("/sys", &format!("{real_root}/sys"));
    mount_move("/dev", &format!("{real_root}/dev"));

    // Copy clone-agent from initrd to rootfs if present
    let agent_initrd = Path::new("/clone-agent");
    if agent_initrd.exists() {
        let agent_dest = format!("{real_root}/usr/local/bin/clone-agent");
        mkdir(&format!("{real_root}/usr/local/bin"));
        msg(&format!("[clone-init] copying agent to {agent_dest}"));
        if fs::copy("/clone-agent", &agent_dest).is_ok() {
            // Make executable
            #[cfg(target_os = "linux")]
            unsafe {
                let c_path = CString::new(agent_dest.as_str()).unwrap();
                libc::chmod(c_path.as_ptr(), 0o755);
            }
            msg("[clone-init] installed clone-agent");
        }
    }

    msg(&format!("[clone-init] switching root to {real_root}"));

    // switch_root: chdir, mount --move ., chroot ., exec /sbin/init
    chdir(real_root);
    mount_move_dot();
    do_chroot(".");

    // Start clone-agent in background before exec'ing init
    if Path::new("/usr/local/bin/clone-agent").exists() {
        msg("[clone-init] starting clone-agent");
        #[cfg(target_os = "linux")]
        unsafe {
            let pid = libc::fork();
            if pid == 0 {
                // Child: become session leader, set up minimal env, exec clone-agent
                libc::setsid();
                // Small delay to let vsock device settle
                libc::usleep(500_000); // 500ms
                let c_path = CString::new("/usr/local/bin/clone-agent").unwrap();
                let c_argv0 = CString::new("clone-agent").unwrap();
                let argv: [*const libc::c_char; 2] = [c_argv0.as_ptr(), std::ptr::null()];
                let c_path_env = CString::new("PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin").unwrap();
                let c_home = CString::new("HOME=/root").unwrap();
                let c_term = CString::new("TERM=linux").unwrap();
                let envp: [*const libc::c_char; 4] = [
                    c_path_env.as_ptr(), c_home.as_ptr(), c_term.as_ptr(), std::ptr::null()
                ];
                libc::execve(c_path.as_ptr(), argv.as_ptr(), envp.as_ptr());
                // If execve fails, write error marker and exit
                let _ = fs::write("/tmp/clone-agent-exec-failed", format!("errno: {}", *libc::__errno_location()));
                libc::_exit(1);
            } else if pid > 0 {
                // agent forked successfully
            }
        }
    }

    // Find init to exec
    let init_paths = ["/sbin/init", "/bin/init", "/lib/systemd/systemd", "/bin/sh"];
    for init in &init_paths {
        if Path::new(init).exists() {
            msg(&format!("[clone-init] exec {init}"));
            do_exec(init);
            // If exec returns, it failed
            msg(&format!("[clone-init] exec {init} failed"));
        }
    }

    panic!("[clone-init] no init found in rootfs");
}

fn read_cmdline() -> String {
    fs::read_to_string("/proc/cmdline").unwrap_or_default()
}

fn parse_param<'a>(cmdline: &'a str, key: &str) -> Option<&'a str> {
    for part in cmdline.split_whitespace() {
        if let Some(val) = part.strip_prefix(&format!("{key}=")) {
            return Some(val);
        }
    }
    None
}

fn mkdir(path: &str) {
    let _ = fs::create_dir_all(path);
}

fn mount_fs(source: &str, target: &str, fstype: &str, flags: u64) -> bool {
    do_mount(source, target, Some(fstype), flags, None)
}

fn mount_move(from: &str, to: &str) {
    if !do_mount(from, to, None, MS_MOVE, None) {
        let err = std::io::Error::last_os_error();
        msg(&format!("[clone-init] mount --move {from} -> {to} failed: {err}"));
    }
}

/// mount --move . / (move current directory to root)
fn mount_move_dot() {
    if !do_mount(".", "/", None, MS_MOVE, None) {
        let err = std::io::Error::last_os_error();
        msg(&format!("[clone-init] mount --move . / failed: {err}"));
    }
}

#[cfg(target_os = "linux")]
fn do_mount(source: &str, target: &str, fstype: Option<&str>, flags: u64, data: Option<&str>) -> bool {
    let c_source = CString::new(source).unwrap();
    let c_target = CString::new(target).unwrap();
    let c_fstype = fstype.map(|s| CString::new(s).unwrap());
    let c_data = data.map(|s| CString::new(s).unwrap());

    let ret = unsafe {
        libc::mount(
            c_source.as_ptr(),
            c_target.as_ptr(),
            c_fstype.as_ref().map_or(std::ptr::null(), |s| s.as_ptr()),
            flags,
            c_data.as_ref().map_or(std::ptr::null(), |s| s.as_ptr() as *const libc::c_void),
        )
    };
    ret == 0
}

#[cfg(not(target_os = "linux"))]
fn do_mount(_source: &str, _target: &str, _fstype: Option<&str>, _flags: u64, _data: Option<&str>) -> bool {
    // Stub for non-Linux — this binary only runs inside a Linux guest.
    false
}

fn chdir(path: &str) {
    let c_path = CString::new(path).unwrap();
    unsafe {
        libc::chdir(c_path.as_ptr());
    }
}

#[cfg(target_os = "linux")]
fn do_chroot(path: &str) {
    let c_path = CString::new(path).unwrap();
    let ret = unsafe { libc::chroot(c_path.as_ptr()) };
    if ret != 0 {
        let err = std::io::Error::last_os_error();
        msg(&format!("[clone-init] chroot {path} failed: {err}"));
    }
}

#[cfg(not(target_os = "linux"))]
fn do_chroot(_path: &str) {}

fn do_exec(path: &str) {
    let c_path = CString::new(path).unwrap();
    // argv[0] = "init", NULL-terminated
    let c_init = CString::new("init").unwrap();
    let argv = [c_init.as_ptr(), std::ptr::null()];
    // Clean environment
    let c_term = CString::new("TERM=linux").unwrap();
    let c_home = CString::new("HOME=/root").unwrap();
    let c_path_env = CString::new("PATH=/sbin:/bin:/usr/sbin:/usr/bin").unwrap();
    let envp = [c_term.as_ptr(), c_home.as_ptr(), c_path_env.as_ptr(), std::ptr::null()];

    unsafe {
        libc::execve(c_path.as_ptr(), argv.as_ptr(), envp.as_ptr());
    }
}

/// Load a kernel module using the init_module syscall.
#[cfg(target_os = "linux")]
fn load_module(path: &str) {
    match fs::read(path) {
        Ok(data) => {
            let params = CString::new("").unwrap();
            let ret = unsafe {
                libc::syscall(
                    libc::SYS_init_module,
                    data.as_ptr() as *const libc::c_void,
                    data.len() as libc::c_ulong,
                    params.as_ptr(),
                )
            };
            if ret == 0 {
                msg(&format!("[clone-init] loaded module {path}"));
            } else {
                let err = std::io::Error::last_os_error();
                msg(&format!("[clone-init] failed to load {path}: {err}"));
            }
        }
        Err(e) => {
            msg(&format!("[clone-init] could not read {path}: {e}"));
        }
    }
}

#[cfg(not(target_os = "linux"))]
fn load_module(_path: &str) {}

fn wait_for_device(path: &str) {
    for i in 0..50 {
        if Path::new(path).exists() {
            return;
        }
        if i == 0 {
            msg(&format!("[clone-init] waiting for {path}..."));
        }
        thread::sleep(Duration::from_millis(100));
    }
    panic!("[clone-init] device {path} did not appear after 5s");
}

/// Set up overlayfs with tmpfs as the writable upper layer.
/// Lower = /mnt/root (the read-only rootfs)
/// Upper = /mnt/overlay/upper (tmpfs)
/// Work  = /mnt/overlay/work (tmpfs)
/// Merged = /mnt/merged
fn setup_overlay_tmpfs() -> &'static str {
    mkdir("/mnt/overlay");
    mount_fs("tmpfs", "/mnt/overlay", "tmpfs", 0);
    mkdir("/mnt/overlay/upper");
    mkdir("/mnt/overlay/work");
    mkdir("/mnt/merged");

    let opts = "lowerdir=/mnt/root,upperdir=/mnt/overlay/upper,workdir=/mnt/overlay/work";
    if !do_mount("overlay", "/mnt/merged", Some("overlay"), 0, Some(opts)) {
        let err = std::io::Error::last_os_error();
        panic!("[clone-init] overlayfs mount failed: {err}");
    }

    msg("[clone-init] overlayfs mounted (lower=/mnt/root, upper=tmpfs)");
    "/mnt/merged"
}

/// Set up overlayfs with a block device (/dev/vdb) as the writable upper layer.
/// The block device is formatted with ext4 on first use if empty.
/// Lower = /mnt/root (the read-only rootfs)
/// Upper = /mnt/overlay/upper (ext4 on /dev/vdb)
/// Work  = /mnt/overlay/work (ext4 on /dev/vdb)
/// Merged = /mnt/merged
fn setup_overlay_block() -> &'static str {
    let overlay_dev = "/dev/vdb";

    // Wait for the overlay block device
    wait_for_device(overlay_dev);

    mkdir("/mnt/overlay");

    // Try to mount as ext4 first (already formatted)
    if !mount_fs(overlay_dev, "/mnt/overlay", "ext4", 0) {
        // Not formatted yet — format it
        msg("[clone-init] formatting overlay device with ext4");
        let status = std::process::Command::new("/sbin/mkfs.ext4")
            .args(["-q", "-F", overlay_dev])
            .status();
        match status {
            Ok(s) if s.success() => {}
            _ => {
                // Try mke2fs as fallback
                let _ = std::process::Command::new("/sbin/mke2fs")
                    .args(["-t", "ext4", "-q", "-F", overlay_dev])
                    .status();
            }
        }
        if !mount_fs(overlay_dev, "/mnt/overlay", "ext4", 0) {
            panic!("[clone-init] failed to mount overlay device {overlay_dev}");
        }
    }

    mkdir("/mnt/overlay/upper");
    mkdir("/mnt/overlay/work");
    mkdir("/mnt/merged");

    let opts = "lowerdir=/mnt/root,upperdir=/mnt/overlay/upper,workdir=/mnt/overlay/work";
    if !do_mount("overlay", "/mnt/merged", Some("overlay"), 0, Some(opts)) {
        let err = std::io::Error::last_os_error();
        panic!("[clone-init] overlayfs mount failed: {err}");
    }

    msg("[clone-init] overlayfs mounted (lower=/mnt/root, upper=block:/dev/vdb)");
    "/mnt/merged"
}
